name: Node.js CI Workflow

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: List directory contents
        run: ls -al

     
      - name: Create a new directory and files under python-practice
        run: |
          # Create a new directory
          mkdir -p .github/workflows/new-directory
          
          # Create some files inside the new directory
          echo "This is a sample file 1" > .github/workflows/new-directory/file1.txt
          echo "This is a sample file 2" > .github/workflows/new-directory/file2.txt
          echo "This is a sample file 3" > .github/workflows/new-directory/file3.txt

          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
           .github/workflows/new-directory/my-file.txt

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: .github/workflows/new-directory/my-file.txt  # Ensure path is correct
          

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact  # Ensure this matches the upload name

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

       

