name: Node.js CI Workflow

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: List directory contents
        run: ls -al

      - name: Create a new directory and files under python-practice
        run: |
          # Create a new directory
          mkdir -p python-practice/new-directory
          
          # Create some files inside the new directory
          echo "This is a sample file 1" > python-practice/new-directory/file1.txt
          echo "This is a sample file 2" > python-practice/new-directory/file2.txt
          echo "This is a sample file 3" > python-practice/new-directory/file3.txt

      - name: npm install, build, and test
        run: |
          cd python-practice  # Ensure we're in the correct directory
          npm install
          npm run build --if-present
          npm test
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my_file.txt
          retention-days: 5

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

