name: Manual Workflow
on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
      - name: Run a script
        run: echo "This is a manually triggered workflow."
      - name: Create files directory
        run: mkdir -p files
      - name: Upload artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: my-artifact
          path: |
            files/**
            package.json

