name: Sequential Example

on:
 workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Running Step 1"
  job2:
    runs-on: ubuntu-latest
    needs: job1  # job2 depends on job1
    steps:
      - name: Step 2
        run: echo "Running Step 2"

