name: Sequential Example with Needs

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: checkout  # This job depends on the 'checkout' job to finish successfully
    steps:
      - name: List files for debugging
        run: ls -R  # List files to see where requirements.txt is located

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt 

      - name: Run tests (Python)
        run: |
          pytest

      - name: Statement
        run: |
          echo "output of yaml file"

        run: |
          echo "output of yaml file"
