name: Sequential Example

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests (Python)
        run: |
          pytest

      # If you're using npm for frontend, make sure to move to the right directory
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # or your desired Node version

      - name: Install npm dependencies
        run: |
          cd frontend  
          npm install

      - name: Run npm tests
        run: |
          cd frontend  # Navigate to the correct directory again
          npm test

      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy to production
        run: |
          ./deploy.sh
