name: Sequential Example with Needs

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: checkout  
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run tests (Python)
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest 
          pytest test_sample.py

      - name: Statement
        run: |
          echo "output of yaml file".
