name: Sequential Example with Needs

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: checkout  # This job depends on the 'checkout' job
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest

      - name: Statement
        run: |
          echo "This is the statement step running after all tests have completed."
