name: Testcases run

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd apple_project
        python -m pip install --upgrade pip
        pip freeze > requirements.txt

        

        # Create virtual environment
        python -m venv playwright_env
        source playwright_env/bin/activate
        
        # Install Playwright and other dependencies
        pip install pytest-playwright
        playwright install

    - name: Run tests
      run: |
        # Make sure you are in the correct directory to run the tests
        cd apple_project/tests
        pip install -U pytest
        pip install selenium
        pip install webdriver-manager
        pytest test_addfeatures.py  
