name: Testcases run

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cd keka_portal_automation
        python -m pip install --upgrade pip

        # Create virtual environment
        python -m venv playwright_env
        source playwright_env/bin/activate
        
        # Install Playwright and other dependencies
        pip install pytest-playwright
        playwright install

    - name: Run tests
      run: |
        # Make sure you are in the correct directory to run the tests
        cd keka_portal_automation/test_cases
        pytest test_Homefunctionality.py  
