name: Testcases run

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd apple_project
        python -m pip install --upgrade pip
        pip freeze > requirements.txt

        

        # Create virtual environment
        python -m venv project_env
        source project_env/bin/activate
        
       

    - name: Run tests
      run: |
        # Make sure you are in the correct directory to run the tests
        cd apple_project/tests
        pip install -U pytest
        pip install selenium
        pip install pytest-playwright
        playwright install
        pip install webdriver-manager
        pytest test_addfeatures.py  
   
    - name: Install Allure commandline (Latest Version)
      run: |
        LATEST_ALLURE_VERSION=$(curl -s https://api.github.com/repos/allure-framework/allure2/releases/latest | jq -r .tag_name)
        wget -qO- https://github.com/allure-framework/allure2/releases/download/$LATEST_ALLURE_VERSION/allure-$LATEST_ALLURE_VERSION.tgz | tar xvz -C /tmp
        sudo ln -s /tmp/allure-$LATEST_ALLURE_VERSION/bin/allure /usr/local/bin/allure
